import { defineConfig } from 'vitest/config'
import path from 'node:path'
import ts from 'typescript'

// Transform standard TypeScript decorators before Vite's default parser sees
// source files (port of flowforge's vitest.shared.ts standardDecoratorPlugin).
const decoratorSyntax = /^\s*@[A-Za-z_$][\w$]*/m

function standardDecoratorPlugin() {
  return {
    name: 'flowforge-standard-decorators',
    enforce: 'pre' as const,
    transform(code: string, id: string) {
      const file = id.split('?', 1)[0]!
      if (!/\.[cm]?tsx?$/.test(file) || !decoratorSyntax.test(code)) return
      const result = ts.transpileModule(code, {
        fileName: file,
        compilerOptions: {
          target: ts.ScriptTarget.ES2024,
          module: ts.ModuleKind.ESNext,
          jsx: file.endsWith('x') ? ts.JsxEmit.ReactJSX : undefined,
          sourceMap: true,
        },
      })
      return {
        code: result.outputText.replace(/\n?\/\/# sourceMappingURL=.*$/u, '\n'),
        map: result.sourceMapText,
      }
    },
  }
}

// Process-bound suites exercise process-global state or timing-sensitive
// process I/O that worker threads cannot isolate reliably under aggregate
// gate contention (upstream keeps the same narrow exception in forks).
const processBoundTests = [
  'packages/session/session-persistence-jsonl/tests/jsonl.spec.ts',
  'packages/session/session-persistence-jsonl/tests/zstd.spec.ts',
  'packages/subagent/subagent-acp/tests/subagent-acp.spec.ts',
  'packages/subprocess/subprocess-local/tests/process-exit.spec.ts',
  'packages/subprocess/subprocess-local/tests/spawn.spec.ts',
  'packages/context/time-context/tests/time-context.spec.ts',
  'packages/llm/llm-pi-ai/tests/adapter.spec.ts',
  'packages/workflow/workflow-worker-thread/tests/session.spec.ts',
]

// cats/shared ports its clowder suites as plain .test.js files (vitest-style
// imports, no TS), so the workspace lanes also admit .js test files.
const testInclude = ['tests/**/*.test.ts', 'packages/*/*/tests/**/*.{test,spec}.{ts,js}', 'packages/*/*/test/**/*.{test,spec}.{ts,js}']

// Bash-requiring suites (a real POSIX shell is unavailable on Windows); the
// pwsh suites deliberately stay INCLUDED since PowerShell ships with Windows
// (upstream parity). hooks/* drive their assertions through bash fixtures.
const windowsUnsupportedTests = process.platform === 'win32'
  ? [
      'packages/shell/bash-local/tests/**/*.spec.ts',
      'packages/shell/bash-sandbox/tests/**/*.spec.ts',
      'packages/shell/tool-bash/tests/**/*.spec.ts',
      'packages/hooks/*/tests/**/*.spec.ts',
      'packages/terminal/terminal-bash/tests/**/*.spec.ts',
      'packages/sandbox/sandbox-local/tests/**/*.spec.ts',
      'packages/subprocess/subprocess/tests/**/*.spec.ts',
      'packages/subprocess/subprocess-local/tests/local.spec.ts',
      'packages/subprocess/subprocess-local/tests/process-inspector.spec.ts',
      'packages/subprocess/subprocess-local/tests/spawn.spec.ts',
      'packages/subprocess/subprocess-local/tests/terminal.spec.ts',
    ]
  : []

// Suites that create file symlinks: Windows needs Administrator or Developer
// Mode for fs.symlinkSync, and without either they fail with EPERM. Upstream
// runs these on an elevated Windows lane; re-enable here once this lane has
// Developer Mode turned on.
const windowsSymlinkTests = process.platform === 'win32'
  ? [
      'packages/fs/fs-local/tests/filesystem.spec.ts',
      'packages/fs/fs-local/tests/fsio.spec.ts',
      'packages/fs/fs-sandbox/tests/containment.spec.ts',
      'packages/fs/fs-sandbox/tests/fs-sandbox.spec.ts',
      'packages/lsp/lsp-stdio/tests/host.spec.ts',
      'packages/shell/pwsh-local/tests/executor.spec.ts',
      'packages/skill/skill-filesystem/tests/skill-filesystem.spec.ts',
      'packages/workspace/workspace/tests/workspace.spec.ts',
      'packages/context/agent-instructions/tests/agent-instructions.spec.ts',
    ]
  : []

const testExclude = [
  'node_modules/**',
  'dist/**',
  'web/**',
  'flowforge/**',
  // projection.spec.ts imports @flowforge/host-apiproxy, which lands with the
  // host domain in stage 3; restored then (devDependency removed meanwhile).
  'packages/todo/tool-todo/tests/projection.spec.ts',
  // The loader-smoke driver boots through @flowforge/app-boot (packages/boot),
  // which lands with the vendor domain in stage 3; restored then.
  'packages/shell/tool-pwsh/tests/loader.spec.ts',
  // Deferred catalog lanes (same exclusions as tsconfig.host.json): the
  // generator scripts and committed docs artifacts land with later stages.
  'packages/typert/generator/tests/cordis-catalog.spec.ts',
  'packages/examples/agent-spine-demo/tests/gen-config-catalog.spec.ts',
  ...windowsUnsupportedTests,
  ...windowsSymlinkTests,
]

// Root-level vitest config: every suite forks for Node stability (upstream
// parity); process-bound suites run in a dedicated project for isolation.
// NB: workspace projects build their own vite configs and do NOT inherit the
// root resolve.alias, so the alias list is injected into every project.
const aliasEntries = [
      // zod 3.25.0 ships src-only (no dist/); the @zod/source custom condition
      // points at src/, which TypeScript honours via tsconfig.base.json
      // customConditions but Vite does not. Map `zod` directly to its src so
      // `import { z } from 'zod'` resolves to node_modules/zod/src/index.ts.
      { find: /^zod$/, replacement: path.resolve(import.meta.dirname, 'node_modules/zod/src/index.ts') },
      // tools sub-paths: '@flowforge/tools/src/*' (self-imports spelled with
      // the src/ component) and exports like '@flowforge/tools/invariant'
      // both map into src/; the package's lib/ is not built in test mode.
      // NB: find must NOT end with '/' - rollup-plugin-alias matches with
      // `importee.startsWith(find + '/')`, so a trailing slash would require
      // a double slash to ever match (vite's normalizeAlias only strips the
      // slash when BOTH find and replacement end with one).
      { find: '@flowforge/tools/src', replacement: path.resolve(import.meta.dirname, 'packages/core/tools/src') },
      { find: '@flowforge/tools', replacement: path.resolve(import.meta.dirname, 'packages/core/tools/src') },
      { find: /^@flowforge\/tools$/, replacement: path.resolve(import.meta.dirname, 'packages/core/tools/src') },
// <generated-alias:start>
      { find: '@flowforge/session-title-first-prompt-llm/src', replacement: path.resolve(import.meta.dirname, 'packages/session/session-title-first-prompt-llm/src') },
      { find: '@flowforge/session-title-first-prompt-llm', replacement: path.resolve(import.meta.dirname, 'packages/session/session-title-first-prompt-llm/src') },
      { find: '@flowforge/compaction-tool-result-pruner/src', replacement: path.resolve(import.meta.dirname, 'packages/compaction/compaction-tool-result-pruner/src') },
      { find: '@flowforge/compaction-tool-result-pruner', replacement: path.resolve(import.meta.dirname, 'packages/compaction/compaction-tool-result-pruner/src') },
      { find: '@flowforge/session-title-all-prompts-llm/src', replacement: path.resolve(import.meta.dirname, 'packages/session/session-title-all-prompts-llm/src') },
      { find: '@flowforge/session-title-all-prompts-llm', replacement: path.resolve(import.meta.dirname, 'packages/session/session-title-all-prompts-llm/src') },
      { find: '@flowforge/cordis-plugin-logger-console', replacement: path.resolve(import.meta.dirname, 'vendor/logger-console/src') },
      // cats domain (stage 4): src-only resolution since lib/ is gitignored
      // and unbulked during test runs; aligns with every other @flowforge/* pkg.
      { find: '@flowforge/cats-shared/src', replacement: path.resolve(import.meta.dirname, 'packages/cats/shared/src') },
      { find: '@flowforge/cats-shared', replacement: path.resolve(import.meta.dirname, 'packages/cats/shared/src') },
      { find: /^@flowforge\/cats-shared$/, replacement: path.resolve(import.meta.dirname, 'packages/cats/shared/src') },
      { find: '@flowforge/cats-stores/src', replacement: path.resolve(import.meta.dirname, 'packages/cats/stores/src') },
      { find: '@flowforge/cats-stores', replacement: path.resolve(import.meta.dirname, 'packages/cats/stores/src') },
      { find: /^@flowforge\/cats-stores$/, replacement: path.resolve(import.meta.dirname, 'packages/cats/stores/src') },
      { find: '@flowforge/cats-stores-sqlite/src', replacement: path.resolve(import.meta.dirname, 'packages/cats/stores-sqlite/src') },
      { find: '@flowforge/cats-stores-sqlite', replacement: path.resolve(import.meta.dirname, 'packages/cats/stores-sqlite/src') },
      { find: /^@flowforge\/cats-stores-sqlite$/, replacement: path.resolve(import.meta.dirname, 'packages/cats/stores-sqlite/src') },
      { find: '@flowforge/cats-invocation/src', replacement: path.resolve(import.meta.dirname, 'packages/cats/invocation/src') },
      { find: '@flowforge/cats-invocation', replacement: path.resolve(import.meta.dirname, 'packages/cats/invocation/src') },
      { find: /^@flowforge\/cats-invocation$/, replacement: path.resolve(import.meta.dirname, 'packages/cats/invocation/src') },
      { find: '@flowforge/cats-orchestration/src', replacement: path.resolve(import.meta.dirname, 'packages/cats/orchestration/src') },
      { find: '@flowforge/cats-orchestration', replacement: path.resolve(import.meta.dirname, 'packages/cats/orchestration/src') },
      { find: /^@flowforge\/cats-orchestration$/, replacement: path.resolve(import.meta.dirname, 'packages/cats/orchestration/src') },
      { find: '@flowforge/cats-session/src', replacement: path.resolve(import.meta.dirname, 'packages/cats/session/src') },
      { find: '@flowforge/cats-session', replacement: path.resolve(import.meta.dirname, 'packages/cats/session/src') },
      { find: /^@flowforge\/cats-session$/, replacement: path.resolve(import.meta.dirname, 'packages/cats/session/src') },
      // chat domain (stage 5): src-only resolution since lib/ is gitignored
      // and unbulked during test runs; aligns with every other @flowforge/* pkg.
      { find: '@flowforge/chat-threads/src', replacement: path.resolve(import.meta.dirname, 'packages/chat/threads/src') },
      { find: '@flowforge/chat-threads', replacement: path.resolve(import.meta.dirname, 'packages/chat/threads/src') },
      { find: /^@flowforge\/chat-threads$/, replacement: path.resolve(import.meta.dirname, 'packages/chat/threads/src') },
      { find: '@flowforge/chat-messages/src', replacement: path.resolve(import.meta.dirname, 'packages/chat/messages/src') },
      { find: '@flowforge/chat-messages', replacement: path.resolve(import.meta.dirname, 'packages/chat/messages/src') },
      { find: /^@flowforge\/chat-messages$/, replacement: path.resolve(import.meta.dirname, 'packages/chat/messages/src') },
      { find: '@flowforge/chat-realtime/src', replacement: path.resolve(import.meta.dirname, 'packages/chat/realtime/src') },
      { find: '@flowforge/chat-realtime', replacement: path.resolve(import.meta.dirname, 'packages/chat/realtime/src') },
      { find: /^@flowforge\/chat-realtime$/, replacement: path.resolve(import.meta.dirname, 'packages/chat/realtime/src') },
      { find: '@flowforge/chat-approval/src', replacement: path.resolve(import.meta.dirname, 'packages/chat/approval/src') },
      { find: '@flowforge/chat-approval', replacement: path.resolve(import.meta.dirname, 'packages/chat/approval/src') },
      { find: /^@flowforge\/chat-approval$/, replacement: path.resolve(import.meta.dirname, 'packages/chat/approval/src') },
      { find: '@flowforge/chat-mention/src', replacement: path.resolve(import.meta.dirname, 'packages/chat/mention/src') },
      { find: '@flowforge/chat-mention', replacement: path.resolve(import.meta.dirname, 'packages/chat/mention/src') },
      { find: /^@flowforge\/chat-mention$/, replacement: path.resolve(import.meta.dirname, 'packages/chat/mention/src') },
      { find: '@flowforge/chat-session-chain/src', replacement: path.resolve(import.meta.dirname, 'packages/chat/session-chain/src') },
      { find: '@flowforge/chat-session-chain', replacement: path.resolve(import.meta.dirname, 'packages/chat/session-chain/src') },
      { find: /^@flowforge\/chat-session-chain$/, replacement: path.resolve(import.meta.dirname, 'packages/chat/session-chain/src') },
      { find: '@flowforge/chat-misc/src', replacement: path.resolve(import.meta.dirname, 'packages/chat/misc/src') },
      { find: '@flowforge/chat-misc', replacement: path.resolve(import.meta.dirname, 'packages/chat/misc/src') },
      { find: /^@flowforge\/chat-misc$/, replacement: path.resolve(import.meta.dirname, 'packages/chat/misc/src') },
      { find: '@flowforge/chat-stretch/src', replacement: path.resolve(import.meta.dirname, 'packages/chat/stretch-ports/src') },
      { find: '@flowforge/chat-stretch', replacement: path.resolve(import.meta.dirname, 'packages/chat/stretch-ports/src') },
      { find: /^@flowforge\/chat-stretch$/, replacement: path.resolve(import.meta.dirname, 'packages/chat/stretch-ports/src') },
      { find: '@flowforge/forgekin-e2e/src', replacement: path.resolve(import.meta.dirname, 'packages/forgekin/e2e/src') },
      { find: '@flowforge/forgekin-e2e', replacement: path.resolve(import.meta.dirname, 'packages/forgekin/e2e/src') },
      { find: '@flowforge/chat-e2e/src', replacement: path.resolve(import.meta.dirname, 'packages/chat/e2e/src') },
      { find: '@flowforge/chat-e2e', replacement: path.resolve(import.meta.dirname, 'packages/chat/e2e/src') },
      { find: /^@flowforge\/chat-e2e$/, replacement: path.resolve(import.meta.dirname, 'packages/chat/e2e/src') },
      { find: '@flowforge/limb-core/src', replacement: path.resolve(import.meta.dirname, 'packages/limb/core/src') },
      { find: '@flowforge/limb-core', replacement: path.resolve(import.meta.dirname, 'packages/limb/core/src') },
      { find: /^@flowforge\/limb-core$/, replacement: path.resolve(import.meta.dirname, 'packages/limb/core/src') },
      { find: '@flowforge/limb-adapters/src', replacement: path.resolve(import.meta.dirname, 'packages/limb/adapters/src') },
      { find: '@flowforge/limb-adapters', replacement: path.resolve(import.meta.dirname, 'packages/limb/adapters/src') },
      { find: /^@flowforge\/limb-adapters$/, replacement: path.resolve(import.meta.dirname, 'packages/limb/adapters/src') },
      { find: '@flowforge/limb-embodiment/src', replacement: path.resolve(import.meta.dirname, 'packages/limb/embodiment/src') },
      { find: '@flowforge/limb-embodiment', replacement: path.resolve(import.meta.dirname, 'packages/limb/embodiment/src') },
      { find: /^@flowforge\/limb-embodiment$/, replacement: path.resolve(import.meta.dirname, 'packages/limb/embodiment/src') },
      { find: '@flowforge/limb-node/src', replacement: path.resolve(import.meta.dirname, 'packages/limb/node/src') },
      { find: '@flowforge/limb-node', replacement: path.resolve(import.meta.dirname, 'packages/limb/node/src') },
      { find: /^@flowforge\/limb-node$/, replacement: path.resolve(import.meta.dirname, 'packages/limb/node/src') },
      { find: '@flowforge/limb-observation/src', replacement: path.resolve(import.meta.dirname, 'packages/limb/observation/src') },
      { find: '@flowforge/limb-observation', replacement: path.resolve(import.meta.dirname, 'packages/limb/observation/src') },
      { find: /^@flowforge\/limb-observation$/, replacement: path.resolve(import.meta.dirname, 'packages/limb/observation/src') },
      { find: '@flowforge/limb-terminal/src', replacement: path.resolve(import.meta.dirname, 'packages/limb/terminal/src') },
      { find: '@flowforge/limb-terminal', replacement: path.resolve(import.meta.dirname, 'packages/limb/terminal/src') },
      { find: /^@flowforge\/limb-terminal$/, replacement: path.resolve(import.meta.dirname, 'packages/limb/terminal/src') },
      { find: '@flowforge/forgekin-soul/src', replacement: path.resolve(import.meta.dirname, 'packages/forgekin/soul/src') },
      { find: '@flowforge/forgekin-soul', replacement: path.resolve(import.meta.dirname, 'packages/forgekin/soul/src') },
      { find: /^@flowforge\/forgekin-soul$/, replacement: path.resolve(import.meta.dirname, 'packages/forgekin/soul/src') },
      { find: '@flowforge/forgekin-capability/src', replacement: path.resolve(import.meta.dirname, 'packages/forgekin/capability/src') },
      { find: '@flowforge/forgekin-capability', replacement: path.resolve(import.meta.dirname, 'packages/forgekin/capability/src') },
      { find: /^@flowforge\/forgekin-capability$/, replacement: path.resolve(import.meta.dirname, 'packages/forgekin/capability/src') },
      { find: '@flowforge/forgekin-memory/src', replacement: path.resolve(import.meta.dirname, 'packages/forgekin/memory/src') },
      { find: '@flowforge/forgekin-memory', replacement: path.resolve(import.meta.dirname, 'packages/forgekin/memory/src') },
      { find: /^@flowforge\/forgekin-memory$/, replacement: path.resolve(import.meta.dirname, 'packages/forgekin/memory/src') },
      { find: '@flowforge/forgekin-knowledge/src', replacement: path.resolve(import.meta.dirname, 'packages/forgekin/knowledge/src') },
      { find: '@flowforge/forgekin-knowledge', replacement: path.resolve(import.meta.dirname, 'packages/forgekin/knowledge/src') },
      { find: /^@flowforge\/forgekin-knowledge$/, replacement: path.resolve(import.meta.dirname, 'packages/forgekin/knowledge/src') },
      { find: '@flowforge/forgekin-council/src', replacement: path.resolve(import.meta.dirname, 'packages/forgekin/council/src') },
      { find: '@flowforge/forgekin-council', replacement: path.resolve(import.meta.dirname, 'packages/forgekin/council/src') },
      { find: /^@flowforge\/forgekin-council$/, replacement: path.resolve(import.meta.dirname, 'packages/forgekin/council/src') },
      { find: '@flowforge/forgekin-stage/src', replacement: path.resolve(import.meta.dirname, 'packages/forgekin/stage/src') },
      { find: '@flowforge/forgekin-stage', replacement: path.resolve(import.meta.dirname, 'packages/forgekin/stage/src') },
      { find: /^@flowforge\/forgekin-stage$/, replacement: path.resolve(import.meta.dirname, 'packages/forgekin/stage/src') },
      { find: '@flowforge/forgekin-loops/src', replacement: path.resolve(import.meta.dirname, 'packages/forgekin/loops/src') },
      { find: '@flowforge/forgekin-loops', replacement: path.resolve(import.meta.dirname, 'packages/forgekin/loops/src') },
      { find: /^@flowforge\/forgekin-loops$/, replacement: path.resolve(import.meta.dirname, 'packages/forgekin/loops/src') },
      { find: '@flowforge/forgekin-workflow-compiler/src', replacement: path.resolve(import.meta.dirname, 'packages/forgekin/workflow-compiler/src') },
      { find: '@flowforge/forgekin-workflow-compiler', replacement: path.resolve(import.meta.dirname, 'packages/forgekin/workflow-compiler/src') },
      { find: /^@flowforge\/forgekin-workflow-compiler$/, replacement: path.resolve(import.meta.dirname, 'packages/forgekin/workflow-compiler/src') },
      { find: '@flowforge/forgekin-external-agents/src', replacement: path.resolve(import.meta.dirname, 'packages/forgekin/external-agents/src') },
      { find: '@flowforge/forgekin-external-agents', replacement: path.resolve(import.meta.dirname, 'packages/forgekin/external-agents/src') },
      { find: /^@flowforge\/forgekin-external-agents$/, replacement: path.resolve(import.meta.dirname, 'packages/forgekin/external-agents/src') },
            { find: '@flowforge/forgekin-im-council/src', replacement: path.resolve(import.meta.dirname, 'packages/forgekin/im-council/src') },
      { find: '@flowforge/forgekin-im-council', replacement: path.resolve(import.meta.dirname, 'packages/forgekin/im-council/src') },
      { find: '@flowforge/resilience/src', replacement: path.resolve(import.meta.dirname, 'packages/plugins/resilience/src') },
      { find: '@flowforge/resilience', replacement: path.resolve(import.meta.dirname, 'packages/plugins/resilience/src') },
      { find: '@flowforge/forgekin-magic-words/src', replacement: path.resolve(import.meta.dirname, 'packages/forgekin/magic-words/src') },
            { find: '@flowforge/forgekin-magic-words', replacement: path.resolve(import.meta.dirname, 'packages/forgekin/magic-words/src') },
            { find: /^@flowforge\/forgekin-magic-words$/, replacement: path.resolve(import.meta.dirname, 'packages/forgekin/magic-words/src') },
            { find: '@flowforge/forgekin-sop/src', replacement: path.resolve(import.meta.dirname, 'packages/forgekin/sop/src') },
            { find: '@flowforge/forgekin-sop', replacement: path.resolve(import.meta.dirname, 'packages/forgekin/sop/src') },
            { find: /^@flowforge\/forgekin-sop$/, replacement: path.resolve(import.meta.dirname, 'packages/forgekin/sop/src') },
            { find: '@flowforge/forgekin-swarm/src', replacement: path.resolve(import.meta.dirname, 'packages/forgekin/swarm/src') },
            { find: '@flowforge/forgekin-swarm', replacement: path.resolve(import.meta.dirname, 'packages/forgekin/swarm/src') },
            { find: /^@flowforge\/forgekin-swarm$/, replacement: path.resolve(import.meta.dirname, 'packages/forgekin/swarm/src') },
                        { find: '@flowforge/forgekin-trae-bridge/src', replacement: path.resolve(import.meta.dirname, 'packages/forgekin/trae-bridge/src') },
                        { find: '@flowforge/forgekin-trae-bridge', replacement: path.resolve(import.meta.dirname, 'packages/forgekin/trae-bridge/src') },
                        { find: /^@flowforge\/forgekin-trae-bridge$/, replacement: path.resolve(import.meta.dirname, 'packages/forgekin/trae-bridge/src') },
                        { find: '@flowforge/forgekin-species/src', replacement: path.resolve(import.meta.dirname, 'packages/forgekin/species/src') },
                        { find: '@flowforge/forgekin-species', replacement: path.resolve(import.meta.dirname, 'packages/forgekin/species/src') },
                        { find: /^@flowforge\/forgekin-species$/, replacement: path.resolve(import.meta.dirname, 'packages/forgekin/species/src') },
                        { find: '@flowforge/forgekin-forging/src', replacement: path.resolve(import.meta.dirname, 'packages/forgekin/forging/src') },
                        { find: '@flowforge/forgekin-forging', replacement: path.resolve(import.meta.dirname, 'packages/forgekin/forging/src') },
                        { find: /^@flowforge\/forgekin-forging$/, replacement: path.resolve(import.meta.dirname, 'packages/forgekin/forging/src') },
                                                { find: '@flowforge/forgekin-eval-ledger/src', replacement: path.resolve(import.meta.dirname, 'packages/forgekin/eval-ledger/src') },
                                                { find: '@flowforge/forgekin-eval-ledger', replacement: path.resolve(import.meta.dirname, 'packages/forgekin/eval-ledger/src') },
                                                { find: /^@flowforge\/forgekin-eval-ledger$/, replacement: path.resolve(import.meta.dirname, 'packages/forgekin/eval-ledger/src') },
                        { find: '@flowforge/forgekin-auto-dream/src', replacement: path.resolve(import.meta.dirname, 'packages/forgekin/auto-dream/src') },
                        { find: '@flowforge/forgekin-auto-dream', replacement: path.resolve(import.meta.dirname, 'packages/forgekin/auto-dream/src') },
                        { find: /^@flowforge\/forgekin-auto-dream$/, replacement: path.resolve(import.meta.dirname, 'packages/forgekin/auto-dream/src') },
                        { find: '@flowforge/forgekin-autonomous/src', replacement: path.resolve(import.meta.dirname, 'packages/forgekin/autonomous/src') },
                        { find: '@flowforge/forgekin-autonomous', replacement: path.resolve(import.meta.dirname, 'packages/forgekin/autonomous/src') },
                        { find: /^@flowforge\/forgekin-autonomous$/, replacement: path.resolve(import.meta.dirname, 'packages/forgekin/autonomous/src') },
                        { find: '@flowforge/forgekin-evolution-engine/src', replacement: path.resolve(import.meta.dirname, 'packages/forgekin/evolution-engine/src') },
                        { find: '@flowforge/forgekin-evolution-engine', replacement: path.resolve(import.meta.dirname, 'packages/forgekin/evolution-engine/src') },
                        { find: /^@flowforge\/forgekin-evolution-engine$/, replacement: path.resolve(import.meta.dirname, 'packages/forgekin/evolution-engine/src') },
                        { find: '@flowforge/forgekin-stores/src', replacement: path.resolve(import.meta.dirname, 'packages/forgekin/stores/src') },
                        { find: '@flowforge/forgekin-stores', replacement: path.resolve(import.meta.dirname, 'packages/forgekin/stores/src') },
                        { find: /^@flowforge\/forgekin-stores$/, replacement: path.resolve(import.meta.dirname, 'packages/forgekin/stores/src') },
                        { find: '@flowforge/forgekin-observability/src', replacement: path.resolve(import.meta.dirname, 'packages/forgekin/observability/src') },
                        { find: '@flowforge/forgekin-observability', replacement: path.resolve(import.meta.dirname, 'packages/forgekin/observability/src') },
                        { find: /^@flowforge\/forgekin-observability$/, replacement: path.resolve(import.meta.dirname, 'packages/forgekin/observability/src') },
                        { find: '@flowforge/forgekin-capabilities/src', replacement: path.resolve(import.meta.dirname, 'packages/forgekin/capabilities/src') },
                        { find: '@flowforge/forgekin-capabilities', replacement: path.resolve(import.meta.dirname, 'packages/forgekin/capabilities/src') },
                        { find: /^@flowforge\/forgekin-capabilities$/, replacement: path.resolve(import.meta.dirname, 'packages/forgekin/capabilities/src') },
                        { find: '@flowforge/forgekin-governance/src', replacement: path.resolve(import.meta.dirname, 'packages/forgekin/governance/src') },
                        { find: '@flowforge/forgekin-governance', replacement: path.resolve(import.meta.dirname, 'packages/forgekin/governance/src') },
                        { find: /^@flowforge\/forgekin-governance$/, replacement: path.resolve(import.meta.dirname, 'packages/forgekin/governance/src') },
                        { find: '@flowforge/infrastructure-commands/src', replacement: path.resolve(import.meta.dirname, 'packages/infrastructure/commands/src') },
                        { find: '@flowforge/infrastructure-commands', replacement: path.resolve(import.meta.dirname, 'packages/infrastructure/commands/src') },
                        { find: /^@flowforge\/infrastructure-commands$/, replacement: path.resolve(import.meta.dirname, 'packages/infrastructure/commands/src') },
                        { find: '@flowforge/infrastructure-distillation/src', replacement: path.resolve(import.meta.dirname, 'packages/infrastructure/distillation/src') },
                        { find: '@flowforge/infrastructure-distillation', replacement: path.resolve(import.meta.dirname, 'packages/infrastructure/distillation/src') },
                        { find: /^@flowforge\/infrastructure-distillation$/, replacement: path.resolve(import.meta.dirname, 'packages/infrastructure/distillation/src') },
                        { find: '@flowforge/infrastructure-document/src', replacement: path.resolve(import.meta.dirname, 'packages/infrastructure/document/src') },
                        { find: '@flowforge/infrastructure-document', replacement: path.resolve(import.meta.dirname, 'packages/infrastructure/document/src') },
                        { find: /^@flowforge\/infrastructure-document$/, replacement: path.resolve(import.meta.dirname, 'packages/infrastructure/document/src') },
                        { find: '@flowforge/infrastructure-telemetry/src', replacement: path.resolve(import.meta.dirname, 'packages/infrastructure/telemetry/src') },
                        { find: '@flowforge/infrastructure-telemetry', replacement: path.resolve(import.meta.dirname, 'packages/infrastructure/telemetry/src') },
                        { find: /^@flowforge\/infrastructure-telemetry$/, replacement: path.resolve(import.meta.dirname, 'packages/infrastructure/telemetry/src') },
                        { find: '@flowforge/infrastructure-debug/src', replacement: path.resolve(import.meta.dirname, 'packages/infrastructure/debug/src') },
                        { find: '@flowforge/infrastructure-debug', replacement: path.resolve(import.meta.dirname, 'packages/infrastructure/debug/src') },
                        { find: /^@flowforge\/infrastructure-debug$/, replacement: path.resolve(import.meta.dirname, 'packages/infrastructure/debug/src') },
                        { find: '@flowforge/infrastructure-scheduler/src', replacement: path.resolve(import.meta.dirname, 'packages/infrastructure/scheduler/src') },
                        { find: '@flowforge/infrastructure-scheduler', replacement: path.resolve(import.meta.dirname, 'packages/infrastructure/scheduler/src') },
                        { find: /^@flowforge\/infrastructure-scheduler$/, replacement: path.resolve(import.meta.dirname, 'packages/infrastructure/scheduler/src') },
                        { find: '@flowforge/infrastructure-github/src', replacement: path.resolve(import.meta.dirname, 'packages/infrastructure/github/src') },
                        { find: '@flowforge/infrastructure-github', replacement: path.resolve(import.meta.dirname, 'packages/infrastructure/github/src') },
                        { find: /^@flowforge\/infrastructure-github$/, replacement: path.resolve(import.meta.dirname, 'packages/infrastructure/github/src') },
                        { find: '@flowforge/infrastructure-grounding/src', replacement: path.resolve(import.meta.dirname, 'packages/infrastructure/grounding/src') },
                        { find: '@flowforge/infrastructure-grounding', replacement: path.resolve(import.meta.dirname, 'packages/infrastructure/grounding/src') },
                        { find: /^@flowforge\/infrastructure-grounding$/, replacement: path.resolve(import.meta.dirname, 'packages/infrastructure/grounding/src') },
                        { find: '@flowforge/infrastructure-enterprise/src', replacement: path.resolve(import.meta.dirname, 'packages/infrastructure/enterprise/src') },
                        { find: '@flowforge/infrastructure-enterprise', replacement: path.resolve(import.meta.dirname, 'packages/infrastructure/enterprise/src') },
                        { find: /^@flowforge\/infrastructure-enterprise$/, replacement: path.resolve(import.meta.dirname, 'packages/infrastructure/enterprise/src') },
                        { find: '@flowforge/infrastructure-redis-port/src', replacement: path.resolve(import.meta.dirname, 'packages/infrastructure/redis-port/src') },
                        { find: '@flowforge/infrastructure-redis-port', replacement: path.resolve(import.meta.dirname, 'packages/infrastructure/redis-port/src') },
                        { find: /^@flowforge\/infrastructure-redis-port$/, replacement: path.resolve(import.meta.dirname, 'packages/infrastructure/redis-port/src') },
                        { find: '@flowforge/infrastructure-email/src', replacement: path.resolve(import.meta.dirname, 'packages/infrastructure/email/src') },
                        { find: '@flowforge/infrastructure-email', replacement: path.resolve(import.meta.dirname, 'packages/infrastructure/email/src') },
                        { find: /^@flowforge\/infrastructure-email$/, replacement: path.resolve(import.meta.dirname, 'packages/infrastructure/email/src') },
      { find: '@flowforge/code-runtime-worker-thread/src', replacement: path.resolve(import.meta.dirname, 'packages/code-runtime/code-runtime-worker-thread/src') },
      { find: '@flowforge/code-runtime-worker-thread', replacement: path.resolve(import.meta.dirname, 'packages/code-runtime/code-runtime-worker-thread/src') },
      { find: '@flowforge/session-persistence-sqlite/src', replacement: path.resolve(import.meta.dirname, 'packages/session/session-persistence-sqlite/src') },
      { find: '@flowforge/session-persistence-sqlite', replacement: path.resolve(import.meta.dirname, 'packages/session/session-persistence-sqlite/src') },
      { find: '@flowforge/subagent-in-process-driver/src', replacement: path.resolve(import.meta.dirname, 'packages/subagent/subagent-in-process-driver/src') },
      { find: '@flowforge/subagent-in-process-driver', replacement: path.resolve(import.meta.dirname, 'packages/subagent/subagent-in-process-driver/src') },
      { find: '@flowforge/session-checkpoint-policy/src', replacement: path.resolve(import.meta.dirname, 'packages/session/session-checkpoint-policy/src') },
      { find: '@flowforge/session-checkpoint-policy', replacement: path.resolve(import.meta.dirname, 'packages/session/session-checkpoint-policy/src') },
      { find: '@flowforge/session-persistence-jsonl/src', replacement: path.resolve(import.meta.dirname, 'packages/session/session-persistence-jsonl/src') },
      { find: '@flowforge/session-persistence-jsonl', replacement: path.resolve(import.meta.dirname, 'packages/session/session-persistence-jsonl/src') },
      { find: '@flowforge/subagent-spawn-in-process/src', replacement: path.resolve(import.meta.dirname, 'packages/subagent/subagent-spawn-in-process/src') },
      { find: '@flowforge/subagent-spawn-in-process', replacement: path.resolve(import.meta.dirname, 'packages/subagent/subagent-spawn-in-process/src') },
      { find: '@flowforge/session-projection-cache/src', replacement: path.resolve(import.meta.dirname, 'packages/session/session-projection-cache/src') },
      { find: '@flowforge/session-projection-cache', replacement: path.resolve(import.meta.dirname, 'packages/session/session-projection-cache/src') },
      { find: '@flowforge/subagent-fork-in-process/src', replacement: path.resolve(import.meta.dirname, 'packages/subagent/subagent-fork-in-process/src') },
      { find: '@flowforge/subagent-fork-in-process', replacement: path.resolve(import.meta.dirname, 'packages/subagent/subagent-fork-in-process/src') },
      { find: '@flowforge/tool-call-timeout-policy/src', replacement: path.resolve(import.meta.dirname, 'packages/guard/timeout-policy/src') },
      { find: '@flowforge/tool-call-timeout-policy', replacement: path.resolve(import.meta.dirname, 'packages/guard/timeout-policy/src') },
      { find: '@flowforge/agent-tool-presentation/src', replacement: path.resolve(import.meta.dirname, 'packages/core/agent-tool-presentation/src') },
      { find: '@flowforge/agent-tool-presentation', replacement: path.resolve(import.meta.dirname, 'packages/core/agent-tool-presentation/src') },
      { find: '@flowforge/node-addon-landlock-run', replacement: path.resolve(import.meta.dirname, 'native/landlock-run/packages/entry/src') },
      { find: '@flowforge/tool-str-replace-editor/src', replacement: path.resolve(import.meta.dirname, 'packages/fs/tool-str-replace-editor/src') },
      { find: '@flowforge/tool-str-replace-editor', replacement: path.resolve(import.meta.dirname, 'packages/fs/tool-str-replace-editor/src') },
      { find: '@flowforge/session-telemetry-otel/src', replacement: path.resolve(import.meta.dirname, 'packages/session/session-telemetry-otel/src') },
      { find: '@flowforge/session-telemetry-otel', replacement: path.resolve(import.meta.dirname, 'packages/session/session-telemetry-otel/src') },
      { find: '@flowforge/workflow-worker-thread/src', replacement: path.resolve(import.meta.dirname, 'packages/workflow/workflow-worker-thread/src') },
      { find: '@flowforge/workflow-worker-thread', replacement: path.resolve(import.meta.dirname, 'packages/workflow/workflow-worker-thread/src') },
      { find: '@flowforge/cordis-plugin-include', replacement: path.resolve(import.meta.dirname, 'vendor/include/src') },
      { find: '@flowforge/fs-observation-policy/src', replacement: path.resolve(import.meta.dirname, 'packages/fs/fs-observation-policy/src') },
      { find: '@flowforge/fs-observation-policy', replacement: path.resolve(import.meta.dirname, 'packages/fs/fs-observation-policy/src') },
      { find: '@flowforge/tool-subagent-control/src', replacement: path.resolve(import.meta.dirname, 'packages/subagent/tool-subagent-control/src') },
      { find: '@flowforge/tool-subagent-control', replacement: path.resolve(import.meta.dirname, 'packages/subagent/tool-subagent-control/src') },
      { find: '@flowforge/web-search-perplexity/src', replacement: path.resolve(import.meta.dirname, 'packages/web/web-search-perplexity/src') },
      { find: '@flowforge/web-search-perplexity', replacement: path.resolve(import.meta.dirname, 'packages/web/web-search-perplexity/src') },
      { find: '@flowforge/cordis-plugin-loader', replacement: path.resolve(import.meta.dirname, 'vendor/loader/src') },
      { find: '@flowforge/repeat-tool-reminder/src', replacement: path.resolve(import.meta.dirname, 'packages/guard/repeat-tool-reminder/src') },
      { find: '@flowforge/repeat-tool-reminder', replacement: path.resolve(import.meta.dirname, 'packages/guard/repeat-tool-reminder/src') },
      { find: '@flowforge/session-query-sqlite/src', replacement: path.resolve(import.meta.dirname, 'packages/session-query/session-query-sqlite/src') },
      { find: '@flowforge/session-query-sqlite', replacement: path.resolve(import.meta.dirname, 'packages/session-query/session-query-sqlite/src') },
      { find: '@flowforge/subagent-claude-code/src', replacement: path.resolve(import.meta.dirname, 'packages/subagent/subagent-claude-code/src') },
      { find: '@flowforge/subagent-claude-code', replacement: path.resolve(import.meta.dirname, 'packages/subagent/subagent-claude-code/src') },
      { find: '@flowforge/tool-bash-persistent/src', replacement: path.resolve(import.meta.dirname, 'packages/shell/tool-bash-persistent/src') },
      { find: '@flowforge/tool-bash-persistent', replacement: path.resolve(import.meta.dirname, 'packages/shell/tool-bash-persistent/src') },
      { find: '@flowforge/tool-subagent-report/src', replacement: path.resolve(import.meta.dirname, 'packages/subagent/tool-subagent-report/src') },
      { find: '@flowforge/tool-subagent-report', replacement: path.resolve(import.meta.dirname, 'packages/subagent/tool-subagent-report/src') },
      { find: '@flowforge/agent-default-model/src', replacement: path.resolve(import.meta.dirname, 'packages/core/agent-default-model/src') },
      { find: '@flowforge/agent-default-model', replacement: path.resolve(import.meta.dirname, 'packages/core/agent-default-model/src') },
      { find: '@flowforge/cordis-plugin-group', replacement: path.resolve(import.meta.dirname, 'vendor/group/src') },
      { find: '@flowforge/cordis-plugin-timer', replacement: path.resolve(import.meta.dirname, 'vendor/timer/src') },
      { find: '@flowforge/sandbox-windows-acl/src', replacement: path.resolve(import.meta.dirname, 'packages/sandbox/sandbox-windows-acl/src') },
      { find: '@flowforge/sandbox-windows-acl', replacement: path.resolve(import.meta.dirname, 'packages/sandbox/sandbox-windows-acl/src') },
      { find: '@flowforge/session-persistence/src', replacement: path.resolve(import.meta.dirname, 'packages/session/session-persistence/src') },
      { find: '@flowforge/session-persistence', replacement: path.resolve(import.meta.dirname, 'packages/session/session-persistence/src') },
      { find: '@flowforge/web-search-deepseek/src', replacement: path.resolve(import.meta.dirname, 'packages/web/web-search-deepseek/src') },
      { find: '@flowforge/web-search-deepseek', replacement: path.resolve(import.meta.dirname, 'packages/web/web-search-deepseek/src') },
      { find: '@flowforge/context-file-reference/src', replacement: path.resolve(import.meta.dirname, 'packages/context/file-reference/src') },
      { find: '@flowforge/context-file-reference', replacement: path.resolve(import.meta.dirname, 'packages/context/file-reference/src') },
      { find: /^@flowforge\/context-file-reference$/, replacement: path.resolve(import.meta.dirname, 'packages/context/file-reference/src') },
      { find: '@flowforge/context-file-reference-local/src', replacement: path.resolve(import.meta.dirname, 'packages/context/file-reference-local/src') },
      { find: '@flowforge/context-file-reference-local', replacement: path.resolve(import.meta.dirname, 'packages/context/file-reference-local/src') },
      { find: /^@flowforge\/context-file-reference-local$/, replacement: path.resolve(import.meta.dirname, 'packages/context/file-reference-local/src') },
      { find: '@flowforge/agent-instructions/src', replacement: path.resolve(import.meta.dirname, 'packages/context/agent-instructions/src') },
      { find: '@flowforge/agent-instructions', replacement: path.resolve(import.meta.dirname, 'packages/context/agent-instructions/src') },
      { find: '@flowforge/agent-loop-testkit/src', replacement: path.resolve(import.meta.dirname, 'packages/test-support/agent-loop-testkit/src') },
      { find: '@flowforge/agent-loop-testkit', replacement: path.resolve(import.meta.dirname, 'packages/test-support/agent-loop-testkit/src') },
      { find: '@flowforge/cordis-host-runner/src', replacement: path.resolve(import.meta.dirname, 'packages/extensions/cordis-host-runner/src') },
      { find: '@flowforge/cordis-host-runner', replacement: path.resolve(import.meta.dirname, 'packages/extensions/cordis-host-runner/src') },
      { find: '@flowforge/launch-environment/src', replacement: path.resolve(import.meta.dirname, 'packages/util/launch-environment/src') },
      { find: '@flowforge/launch-environment', replacement: path.resolve(import.meta.dirname, 'packages/util/launch-environment/src') },
      { find: '@flowforge/permission-presets/src', replacement: path.resolve(import.meta.dirname, 'packages/interaction/permission-presets/src') },
      { find: '@flowforge/permission-presets', replacement: path.resolve(import.meta.dirname, 'packages/interaction/permission-presets/src') },
      { find: '@flowforge/sdk-jsonrpc-server/src', replacement: path.resolve(import.meta.dirname, 'packages/sdk/server/src') },
      { find: '@flowforge/sdk-jsonrpc-server', replacement: path.resolve(import.meta.dirname, 'packages/sdk/server/src') },
      { find: '@flowforge/session-projection/src', replacement: path.resolve(import.meta.dirname, 'packages/session/session-projection/src') },
      { find: '@flowforge/session-projection', replacement: path.resolve(import.meta.dirname, 'packages/session/session-projection/src') },
      { find: '@flowforge/tool-session-query/src', replacement: path.resolve(import.meta.dirname, 'packages/session-query/tool-session-query/src') },
      { find: '@flowforge/tool-session-query', replacement: path.resolve(import.meta.dirname, 'packages/session-query/tool-session-query/src') },
      { find: '@flowforge/anonymous-user-id/src', replacement: path.resolve(import.meta.dirname, 'packages/identity/anonymous-user-id/src') },
      { find: '@flowforge/anonymous-user-id', replacement: path.resolve(import.meta.dirname, 'packages/identity/anonymous-user-id/src') },
      { find: '@flowforge/cordis-plugin-hmr', replacement: path.resolve(import.meta.dirname, 'vendor/hmr/src') },
      { find: '@flowforge/credentials-local/src', replacement: path.resolve(import.meta.dirname, 'packages/credentials/credentials-local/src') },
      { find: '@flowforge/credentials-local', replacement: path.resolve(import.meta.dirname, 'packages/credentials/credentials-local/src') },
      { find: '@flowforge/goal-round-driver/src', replacement: path.resolve(import.meta.dirname, 'packages/goal/goal-round-driver/src') },
      { find: '@flowforge/goal-round-driver', replacement: path.resolve(import.meta.dirname, 'packages/goal/goal-round-driver/src') },
      { find: '@flowforge/hooks-claude-code/src', replacement: path.resolve(import.meta.dirname, 'packages/hooks/hooks-claude-code/src') },
      { find: '@flowforge/hooks-claude-code', replacement: path.resolve(import.meta.dirname, 'packages/hooks/hooks-claude-code/src') },
      { find: '@flowforge/session-reference/src', replacement: path.resolve(import.meta.dirname, 'packages/context/session-reference/src') },
      { find: '@flowforge/session-reference', replacement: path.resolve(import.meta.dirname, 'packages/context/session-reference/src') },
      { find: '@flowforge/session-telemetry/src', replacement: path.resolve(import.meta.dirname, 'packages/session/session-telemetry/src') },
      { find: '@flowforge/session-telemetry', replacement: path.resolve(import.meta.dirname, 'packages/session/session-telemetry/src') },
      { find: '@flowforge/session-title-llm/src', replacement: path.resolve(import.meta.dirname, 'packages/session/session-title-llm/src') },
      { find: '@flowforge/session-title-llm', replacement: path.resolve(import.meta.dirname, 'packages/session/session-title-llm/src') },
      { find: '@flowforge/agent-spine-demo/src', replacement: path.resolve(import.meta.dirname, 'packages/examples/agent-spine-demo/src') },
      { find: '@flowforge/agent-spine-demo', replacement: path.resolve(import.meta.dirname, 'packages/examples/agent-spine-demo/src') },
      { find: '@flowforge/attachment-local/src', replacement: path.resolve(import.meta.dirname, 'packages/attachment/attachment-local/src') },
      { find: '@flowforge/attachment-local', replacement: path.resolve(import.meta.dirname, 'packages/attachment/attachment-local/src') },
      { find: '@flowforge/command-feedback/src', replacement: path.resolve(import.meta.dirname, 'packages/feedback/command-feedback/src') },
      { find: '@flowforge/command-feedback', replacement: path.resolve(import.meta.dirname, 'packages/feedback/command-feedback/src') },
      { find: '@flowforge/compaction-basic/src', replacement: path.resolve(import.meta.dirname, 'packages/compaction/compaction-basic/src') },
      { find: '@flowforge/compaction-basic', replacement: path.resolve(import.meta.dirname, 'packages/compaction/compaction-basic/src') },
      { find: '@flowforge/message-feedback/src', replacement: path.resolve(import.meta.dirname, 'packages/feedback/message-feedback/src') },
      { find: '@flowforge/message-feedback', replacement: path.resolve(import.meta.dirname, 'packages/feedback/message-feedback/src') },
      { find: '@flowforge/output-retention/src', replacement: path.resolve(import.meta.dirname, 'packages/util/output-retention/src') },
      { find: '@flowforge/output-retention', replacement: path.resolve(import.meta.dirname, 'packages/util/output-retention/src') },
      { find: '@flowforge/skill-filesystem/src', replacement: path.resolve(import.meta.dirname, 'packages/skill/skill-filesystem/src') },
      { find: '@flowforge/skill-filesystem', replacement: path.resolve(import.meta.dirname, 'packages/skill/skill-filesystem/src') },
      { find: '@flowforge/subprocess-local/src', replacement: path.resolve(import.meta.dirname, 'packages/subprocess/subprocess-local/src') },
      { find: '@flowforge/subprocess-local', replacement: path.resolve(import.meta.dirname, 'packages/subprocess/subprocess-local/src') },
      { find: '@flowforge/typert-generator/src', replacement: path.resolve(import.meta.dirname, 'packages/typert/generator/src') },
      { find: '@flowforge/typert-generator', replacement: path.resolve(import.meta.dirname, 'packages/typert/generator/src') },
      { find: '@flowforge/command-compact/src', replacement: path.resolve(import.meta.dirname, 'packages/compaction/command-compact/src') },
      { find: '@flowforge/command-compact', replacement: path.resolve(import.meta.dirname, 'packages/compaction/command-compact/src') },
      { find: '@flowforge/llm-mock-server/src', replacement: path.resolve(import.meta.dirname, 'packages/test-support/llm-mock-server/src') },
      { find: '@flowforge/llm-mock-server', replacement: path.resolve(import.meta.dirname, 'packages/test-support/llm-mock-server/src') },
      { find: '@flowforge/plugin-contract/src', replacement: path.resolve(import.meta.dirname, 'packages/plugin-contract/plugin-contract/src') },
      { find: '@flowforge/plugin-contract', replacement: path.resolve(import.meta.dirname, 'packages/plugin-contract/plugin-contract/src') },
      { find: '@flowforge/subagent-ff-sdk/src', replacement: path.resolve(import.meta.dirname, 'packages/subagent/subagent-ff-sdk/src') },
      { find: '@flowforge/subagent-ff-sdk', replacement: path.resolve(import.meta.dirname, 'packages/subagent/subagent-ff-sdk/src') },
      { find: '@flowforge/typert-protocol/src', replacement: path.resolve(import.meta.dirname, 'packages/typert/protocol/src') },
      { find: '@flowforge/typert-protocol', replacement: path.resolve(import.meta.dirname, 'packages/typert/protocol/src') },
      { find: '@flowforge/typert-registry/src', replacement: path.resolve(import.meta.dirname, 'packages/typert/registry/src') },
      { find: '@flowforge/typert-registry', replacement: path.resolve(import.meta.dirname, 'packages/typert/registry/src') },
      { find: '@flowforge/native-command/src', replacement: path.resolve(import.meta.dirname, 'packages/util/native-command/src') },
      { find: '@flowforge/native-command', replacement: path.resolve(import.meta.dirname, 'packages/util/native-command/src') },
      { find: '@flowforge/sandbox-policy/src', replacement: path.resolve(import.meta.dirname, 'packages/sandbox/sandbox-policy/src') },
      { find: '@flowforge/sandbox-policy', replacement: path.resolve(import.meta.dirname, 'packages/sandbox/sandbox-policy/src') },
      { find: '@flowforge/skill-security/src', replacement: path.resolve(import.meta.dirname, 'packages/plugins/skill-security/src') },
      { find: '@flowforge/skill-security', replacement: path.resolve(import.meta.dirname, 'packages/plugins/skill-security/src') },
      { find: '@flowforge/storage-domain/src', replacement: path.resolve(import.meta.dirname, 'packages/storage/storage-domain/src') },
      { find: '@flowforge/storage-domain', replacement: path.resolve(import.meta.dirname, 'packages/storage/storage-domain/src') },
      { find: '@flowforge/storage-sqlite/src', replacement: path.resolve(import.meta.dirname, 'packages/storage/storage-sqlite/src') },
      { find: '@flowforge/storage-sqlite', replacement: path.resolve(import.meta.dirname, 'packages/storage/storage-sqlite/src') },
      { find: '@flowforge/subagent-codex/src', replacement: path.resolve(import.meta.dirname, 'packages/subagent/subagent-codex/src') },
      { find: '@flowforge/subagent-codex', replacement: path.resolve(import.meta.dirname, 'packages/subagent/subagent-codex/src') },
      { find: '@flowforge/subprocess-e2b/src', replacement: path.resolve(import.meta.dirname, 'packages/e2b/subprocess-e2b/src') },
      { find: '@flowforge/subprocess-e2b', replacement: path.resolve(import.meta.dirname, 'packages/e2b/subprocess-e2b/src') },
      { find: '@flowforge/tool-fs-search/src', replacement: path.resolve(import.meta.dirname, 'packages/fs/tool-fs-search/src') },
      { find: '@flowforge/tool-fs-search', replacement: path.resolve(import.meta.dirname, 'packages/fs/tool-fs-search/src') },
      { find: '@flowforge/user-questions/src', replacement: path.resolve(import.meta.dirname, 'packages/interaction/user-questions/src') },
      { find: '@flowforge/user-questions', replacement: path.resolve(import.meta.dirname, 'packages/interaction/user-questions/src') },
      { find: '@flowforge/web-fetch-http/src', replacement: path.resolve(import.meta.dirname, 'packages/web/web-fetch-http/src') },
      { find: '@flowforge/web-fetch-http', replacement: path.resolve(import.meta.dirname, 'packages/web/web-fetch-http/src') },
      { find: '@flowforge/web-search-exa/src', replacement: path.resolve(import.meta.dirname, 'packages/web/web-search-exa/src') },
      { find: '@flowforge/web-search-exa', replacement: path.resolve(import.meta.dirname, 'packages/web/web-search-exa/src') },
      { find: '@flowforge/agent-presets/src', replacement: path.resolve(import.meta.dirname, 'packages/preset/agent-presets/src') },
      { find: '@flowforge/agent-presets', replacement: path.resolve(import.meta.dirname, 'packages/preset/agent-presets/src') },
      { find: '@flowforge/feature-flags/src', replacement: path.resolve(import.meta.dirname, 'packages/plugins/feature-flags/src') },
      { find: '@flowforge/feature-flags', replacement: path.resolve(import.meta.dirname, 'packages/plugins/feature-flags/src') },
      { find: '@flowforge/hook-protocol/src', replacement: path.resolve(import.meta.dirname, 'packages/hooks/hook-protocol/src') },
      { find: '@flowforge/hook-protocol', replacement: path.resolve(import.meta.dirname, 'packages/hooks/hook-protocol/src') },
      { find: '@flowforge/sandbox-local/src', replacement: path.resolve(import.meta.dirname, 'packages/sandbox/sandbox-local/src') },
      { find: '@flowforge/sandbox-local', replacement: path.resolve(import.meta.dirname, 'packages/sandbox/sandbox-local/src') },
      { find: '@flowforge/session-query/src', replacement: path.resolve(import.meta.dirname, 'packages/session-query/session-query/src') },
      { find: '@flowforge/session-query', replacement: path.resolve(import.meta.dirname, 'packages/session-query/session-query/src') },
      { find: '@flowforge/session-stats/src', replacement: path.resolve(import.meta.dirname, 'packages/session/session-stats/src') },
      { find: '@flowforge/session-stats', replacement: path.resolve(import.meta.dirname, 'packages/session/session-stats/src') },
      { find: '@flowforge/session-title/src', replacement: path.resolve(import.meta.dirname, 'packages/session/session-title/src') },
      { find: '@flowforge/session-title', replacement: path.resolve(import.meta.dirname, 'packages/session/session-title/src') },
      { find: '@flowforge/settings-file/src', replacement: path.resolve(import.meta.dirname, 'packages/settings/settings-file/src') },
      { find: '@flowforge/settings-file', replacement: path.resolve(import.meta.dirname, 'packages/settings/settings-file/src') },
      { find: '@flowforge/system-prompt/src', replacement: path.resolve(import.meta.dirname, 'packages/core/system-prompt/src') },
      { find: '@flowforge/system-prompt', replacement: path.resolve(import.meta.dirname, 'packages/core/system-prompt/src') },
      { find: '@flowforge/terminal-bash/src', replacement: path.resolve(import.meta.dirname, 'packages/terminal/terminal-bash/src') },
      { find: '@flowforge/terminal-bash', replacement: path.resolve(import.meta.dirname, 'packages/terminal/terminal-bash/src') },
      { find: '@flowforge/tool-ask-user/src', replacement: path.resolve(import.meta.dirname, 'packages/interaction/tool-ask-user/src') },
      { find: '@flowforge/tool-ask-user', replacement: path.resolve(import.meta.dirname, 'packages/interaction/tool-ask-user/src') },
      { find: '@flowforge/tool-subagent/src', replacement: path.resolve(import.meta.dirname, 'packages/subagent/tool-subagent/src') },
      { find: '@flowforge/tool-subagent', replacement: path.resolve(import.meta.dirname, 'packages/subagent/tool-subagent/src') },
      { find: '@flowforge/tool-terminal/src', replacement: path.resolve(import.meta.dirname, 'packages/terminal/tool-terminal/src') },
      { find: '@flowforge/tool-terminal', replacement: path.resolve(import.meta.dirname, 'packages/terminal/tool-terminal/src') },
      { find: '@flowforge/tool-workflow/src', replacement: path.resolve(import.meta.dirname, 'packages/workflow/tool-workflow/src') },
      { find: '@flowforge/tool-workflow', replacement: path.resolve(import.meta.dirname, 'packages/workflow/tool-workflow/src') },
      { find: '@flowforge/typert-loader/src', replacement: path.resolve(import.meta.dirname, 'packages/typert/loader/src') },
      { find: '@flowforge/typert-loader', replacement: path.resolve(import.meta.dirname, 'packages/typert/loader/src') },
      { find: '@flowforge/user-approval/src', replacement: path.resolve(import.meta.dirname, 'packages/interaction/user-approval/src') },
      { find: '@flowforge/user-approval', replacement: path.resolve(import.meta.dirname, 'packages/interaction/user-approval/src') },
      { find: '@flowforge/acp-snapshot/src', replacement: path.resolve(import.meta.dirname, 'packages/test-support/acp-snapshot/src') },
      { find: '@flowforge/acp-snapshot', replacement: path.resolve(import.meta.dirname, 'packages/test-support/acp-snapshot/src') },
      { find: '@flowforge/atomic-write/src', replacement: path.resolve(import.meta.dirname, 'packages/util/atomic-write/src') },
      { find: '@flowforge/atomic-write', replacement: path.resolve(import.meta.dirname, 'packages/util/atomic-write/src') },
      { find: '@flowforge/bash-sandbox/src', replacement: path.resolve(import.meta.dirname, 'packages/shell/bash-sandbox/src') },
      { find: '@flowforge/bash-sandbox', replacement: path.resolve(import.meta.dirname, 'packages/shell/bash-sandbox/src') },
      { find: '@flowforge/code-runtime/src', replacement: path.resolve(import.meta.dirname, 'packages/code-runtime/code-runtime/src') },
      { find: '@flowforge/code-runtime', replacement: path.resolve(import.meta.dirname, 'packages/code-runtime/code-runtime/src') },
      { find: '@flowforge/command-goal/src', replacement: path.resolve(import.meta.dirname, 'packages/goal/command-goal/src') },
      { find: '@flowforge/command-goal', replacement: path.resolve(import.meta.dirname, 'packages/goal/command-goal/src') },
      { find: '@flowforge/harness-boot/src', replacement: path.resolve(import.meta.dirname, 'packages/harness/boot/src') },
      { find: '@flowforge/harness-boot', replacement: path.resolve(import.meta.dirname, 'packages/harness/boot/src') },
      { find: '@flowforge/llm-deepseek/src', replacement: path.resolve(import.meta.dirname, 'packages/llm/llm-deepseek/src') },
      { find: '@flowforge/llm-deepseek', replacement: path.resolve(import.meta.dirname, 'packages/llm/llm-deepseek/src') },
      { find: '@flowforge/loader-smoke/src', replacement: path.resolve(import.meta.dirname, 'packages/test-support/loader-smoke/src') },
      { find: '@flowforge/loader-smoke', replacement: path.resolve(import.meta.dirname, 'packages/test-support/loader-smoke/src') },
      { find: '@flowforge/pwsh-sandbox/src', replacement: path.resolve(import.meta.dirname, 'packages/shell/pwsh-sandbox/src') },
      { find: '@flowforge/pwsh-sandbox', replacement: path.resolve(import.meta.dirname, 'packages/shell/pwsh-sandbox/src') },
      { find: '@flowforge/sdk-protocol/src', replacement: path.resolve(import.meta.dirname, 'packages/sdk/protocol/src') },
      { find: '@flowforge/sdk-protocol', replacement: path.resolve(import.meta.dirname, 'packages/sdk/protocol/src') },
      { find: '@flowforge/spill-policy/src', replacement: path.resolve(import.meta.dirname, 'packages/spill/spill-policy/src') },
      { find: '@flowforge/spill-policy', replacement: path.resolve(import.meta.dirname, 'packages/spill/spill-policy/src') },
      { find: '@flowforge/storage-json/src', replacement: path.resolve(import.meta.dirname, 'packages/storage/storage-json/src') },
      { find: '@flowforge/storage-json', replacement: path.resolve(import.meta.dirname, 'packages/storage/storage-json/src') },
      { find: '@flowforge/subagent-acp/src', replacement: path.resolve(import.meta.dirname, 'packages/subagent/subagent-acp/src') },
      { find: '@flowforge/subagent-acp', replacement: path.resolve(import.meta.dirname, 'packages/subagent/subagent-acp/src') },
      { find: '@flowforge/time-context/src', replacement: path.resolve(import.meta.dirname, 'packages/context/time-context/src') },
      { find: '@flowforge/time-context', replacement: path.resolve(import.meta.dirname, 'packages/context/time-context/src') },
      { find: '@flowforge/tmux-context/src', replacement: path.resolve(import.meta.dirname, 'packages/context/tmux-context/src') },
      { find: '@flowforge/tmux-context', replacement: path.resolve(import.meta.dirname, 'packages/context/tmux-context/src') },
      { find: '@flowforge/credentials/src', replacement: path.resolve(import.meta.dirname, 'packages/credentials/credentials/src') },
      { find: '@flowforge/credentials', replacement: path.resolve(import.meta.dirname, 'packages/credentials/credentials/src') },
      { find: '@flowforge/hooks-codex/src', replacement: path.resolve(import.meta.dirname, 'packages/hooks/hooks-codex/src') },
      { find: '@flowforge/hooks-codex', replacement: path.resolve(import.meta.dirname, 'packages/hooks/hooks-codex/src') },
      { find: '@flowforge/schemastery', replacement: path.resolve(import.meta.dirname, 'vendor/schemastery/src') },
      { find: '@flowforge/skill-badge/src', replacement: path.resolve(import.meta.dirname, 'packages/skill/skill-badge/src') },
      { find: '@flowforge/skill-badge', replacement: path.resolve(import.meta.dirname, 'packages/skill/skill-badge/src') },
      { find: '@flowforge/spill-local/src', replacement: path.resolve(import.meta.dirname, 'packages/spill/spill-local/src') },
      { find: '@flowforge/spill-local', replacement: path.resolve(import.meta.dirname, 'packages/spill/spill-local/src') },
      { find: '@flowforge/token-meter/src', replacement: path.resolve(import.meta.dirname, 'packages/llm/token-meter/src') },
      { find: '@flowforge/token-meter', replacement: path.resolve(import.meta.dirname, 'packages/llm/token-meter/src') },
      { find: '@flowforge/llm-openroute/src', replacement: path.resolve(import.meta.dirname, 'packages/llm/openroute/src') },
      { find: '@flowforge/llm-openroute', replacement: path.resolve(import.meta.dirname, 'packages/llm/openroute/src') },
      { find: '@flowforge/tool-cordis/src', replacement: path.resolve(import.meta.dirname, 'packages/extensions/tool-cordis/src') },
      { find: '@flowforge/tool-cordis', replacement: path.resolve(import.meta.dirname, 'packages/extensions/tool-cordis/src') },
      { find: '@flowforge/agent-loop/src', replacement: path.resolve(import.meta.dirname, 'packages/core/agent-loop/src') },
      { find: '@flowforge/agent-loop', replacement: path.resolve(import.meta.dirname, 'packages/core/agent-loop/src') },
      { find: '@flowforge/attachment/src', replacement: path.resolve(import.meta.dirname, 'packages/attachment/attachment/src') },
      { find: '@flowforge/attachment', replacement: path.resolve(import.meta.dirname, 'packages/attachment/attachment/src') },
      { find: '@flowforge/bash-local/src', replacement: path.resolve(import.meta.dirname, 'packages/shell/bash-local/src') },
      { find: '@flowforge/bash-local', replacement: path.resolve(import.meta.dirname, 'packages/shell/bash-local/src') },
      { find: '@flowforge/compaction/src', replacement: path.resolve(import.meta.dirname, 'packages/compaction/compaction/src') },
      { find: '@flowforge/compaction', replacement: path.resolve(import.meta.dirname, 'packages/compaction/compaction/src') },
      { find: '@flowforge/fs-sandbox/src', replacement: path.resolve(import.meta.dirname, 'packages/fs/fs-sandbox/src') },
      { find: '@flowforge/fs-sandbox', replacement: path.resolve(import.meta.dirname, 'packages/fs/fs-sandbox/src') },
      { find: '@flowforge/home-paths/src', replacement: path.resolve(import.meta.dirname, 'packages/util/home-paths/src') },
      { find: '@flowforge/home-paths', replacement: path.resolve(import.meta.dirname, 'packages/util/home-paths/src') },
      { find: '@flowforge/invariants/src', replacement: path.resolve(import.meta.dirname, 'packages/runtime-diagnostics/invariants/src') },
      { find: '@flowforge/invariants', replacement: path.resolve(import.meta.dirname, 'packages/runtime-diagnostics/invariants/src') },
      { find: '@flowforge/jobs-local/src', replacement: path.resolve(import.meta.dirname, 'packages/jobs/jobs-local/src') },
      { find: '@flowforge/jobs-local', replacement: path.resolve(import.meta.dirname, 'packages/jobs/jobs-local/src') },
      { find: '@flowforge/llm-replay/src', replacement: path.resolve(import.meta.dirname, 'packages/test-support/llm-replay/src') },
      { find: '@flowforge/llm-replay', replacement: path.resolve(import.meta.dirname, 'packages/test-support/llm-replay/src') },
      { find: '@flowforge/mcp-client/src', replacement: path.resolve(import.meta.dirname, 'packages/mcp/mcp-client/src') },
      { find: '@flowforge/mcp-client', replacement: path.resolve(import.meta.dirname, 'packages/mcp/mcp-client/src') },
      { find: '@flowforge/pwsh-local/src', replacement: path.resolve(import.meta.dirname, 'packages/shell/pwsh-local/src') },
      { find: '@flowforge/pwsh-local', replacement: path.resolve(import.meta.dirname, 'packages/shell/pwsh-local/src') },
      { find: '@flowforge/resilience/src', replacement: path.resolve(import.meta.dirname, 'packages/plugins/resilience/src') },
      { find: '@flowforge/resilience', replacement: path.resolve(import.meta.dirname, 'packages/plugins/resilience/src') },
      { find: '@flowforge/sdk-client/src', replacement: path.resolve(import.meta.dirname, 'packages/sdk/client/src') },
      { find: '@flowforge/sdk-client', replacement: path.resolve(import.meta.dirname, 'packages/sdk/client/src') },
      { find: '@flowforge/subprocess/src', replacement: path.resolve(import.meta.dirname, 'packages/subprocess/subprocess/src') },
      { find: '@flowforge/subprocess', replacement: path.resolve(import.meta.dirname, 'packages/subprocess/subprocess/src') },
      { find: '@flowforge/tool-ralph/src', replacement: path.resolve(import.meta.dirname, 'packages/workflow/tool-ralph/src') },
      { find: '@flowforge/tool-ralph', replacement: path.resolve(import.meta.dirname, 'packages/workflow/tool-ralph/src') },
      { find: '@flowforge/tool-skill/src', replacement: path.resolve(import.meta.dirname, 'packages/skill/tool-skill/src') },
      { find: '@flowforge/tool-skill', replacement: path.resolve(import.meta.dirname, 'packages/skill/tool-skill/src') },
      { find: '@flowforge/llm-pi-ai/src', replacement: path.resolve(import.meta.dirname, 'packages/llm/llm-pi-ai/src') },
      { find: '@flowforge/llm-pi-ai', replacement: path.resolve(import.meta.dirname, 'packages/llm/llm-pi-ai/src') },
      { find: '@flowforge/llm-retry/src', replacement: path.resolve(import.meta.dirname, 'packages/llm/llm-retry/src') },
      { find: '@flowforge/llm-retry', replacement: path.resolve(import.meta.dirname, 'packages/llm/llm-retry/src') },
      { find: '@flowforge/lsp-stdio/src', replacement: path.resolve(import.meta.dirname, 'packages/lsp/lsp-stdio/src') },
      { find: '@flowforge/lsp-stdio', replacement: path.resolve(import.meta.dirname, 'packages/lsp/lsp-stdio/src') },
      { find: '@flowforge/plan-mode/src', replacement: path.resolve(import.meta.dirname, 'packages/plan/plan-mode/src') },
      { find: '@flowforge/plan-mode', replacement: path.resolve(import.meta.dirname, 'packages/plan/plan-mode/src') },
      { find: '@flowforge/shell-env/src', replacement: path.resolve(import.meta.dirname, 'packages/shell/shell-env/src') },
      { find: '@flowforge/shell-env', replacement: path.resolve(import.meta.dirname, 'packages/shell/shell-env/src') },
      { find: '@flowforge/tool-bash/src', replacement: path.resolve(import.meta.dirname, 'packages/shell/tool-bash/src') },
      { find: '@flowforge/tool-bash', replacement: path.resolve(import.meta.dirname, 'packages/shell/tool-bash/src') },
      { find: '@flowforge/tool-goal/src', replacement: path.resolve(import.meta.dirname, 'packages/goal/tool-goal/src') },
      { find: '@flowforge/tool-goal', replacement: path.resolve(import.meta.dirname, 'packages/goal/tool-goal/src') },
      { find: '@flowforge/tool-jobs/src', replacement: path.resolve(import.meta.dirname, 'packages/jobs/tool-jobs/src') },
      { find: '@flowforge/tool-jobs', replacement: path.resolve(import.meta.dirname, 'packages/jobs/tool-jobs/src') },
      { find: '@flowforge/tool-pwsh/src', replacement: path.resolve(import.meta.dirname, 'packages/shell/tool-pwsh/src') },
      { find: '@flowforge/tool-pwsh', replacement: path.resolve(import.meta.dirname, 'packages/shell/tool-pwsh/src') },
      { find: '@flowforge/tool-todo/src', replacement: path.resolve(import.meta.dirname, 'packages/todo/tool-todo/src') },
      { find: '@flowforge/tool-todo', replacement: path.resolve(import.meta.dirname, 'packages/todo/tool-todo/src') },
      { find: '@flowforge/workspace/src', replacement: path.resolve(import.meta.dirname, 'packages/workspace/workspace/src') },
      { find: '@flowforge/workspace', replacement: path.resolve(import.meta.dirname, 'packages/workspace/workspace/src') },
      { find: '@flowforge/commands/src', replacement: path.resolve(import.meta.dirname, 'packages/interaction/commands/src') },
      { find: '@flowforge/commands', replacement: path.resolve(import.meta.dirname, 'packages/interaction/commands/src') },
      { find: '@flowforge/cosmokit', replacement: path.resolve(import.meta.dirname, 'vendor/cosmokit/src') },
      { find: '@flowforge/fs-local/src', replacement: path.resolve(import.meta.dirname, 'packages/fs/fs-local/src') },
      { find: '@flowforge/fs-local', replacement: path.resolve(import.meta.dirname, 'packages/fs/fs-local/src') },
      { find: '@flowforge/schedule/src', replacement: path.resolve(import.meta.dirname, 'packages/schedule/schedule/src') },
      { find: '@flowforge/schedule', replacement: path.resolve(import.meta.dirname, 'packages/schedule/schedule/src') },
      { find: '@flowforge/settings/src', replacement: path.resolve(import.meta.dirname, 'packages/settings/settings/src') },
      { find: '@flowforge/settings', replacement: path.resolve(import.meta.dirname, 'packages/settings/settings/src') },
      { find: '@flowforge/subagent/src', replacement: path.resolve(import.meta.dirname, 'packages/subagent/subagent/src') },
      { find: '@flowforge/subagent', replacement: path.resolve(import.meta.dirname, 'packages/subagent/subagent/src') },
      { find: '@flowforge/terminal/src', replacement: path.resolve(import.meta.dirname, 'packages/terminal/terminal/src') },
      { find: '@flowforge/terminal', replacement: path.resolve(import.meta.dirname, 'packages/terminal/terminal/src') },
      { find: '@flowforge/tool-lsp/src', replacement: path.resolve(import.meta.dirname, 'packages/lsp/tool-lsp/src') },
      { find: '@flowforge/tool-lsp', replacement: path.resolve(import.meta.dirname, 'packages/lsp/tool-lsp/src') },
      { find: '@flowforge/tool-web/src', replacement: path.resolve(import.meta.dirname, 'packages/web/tool-web/src') },
      { find: '@flowforge/tool-web', replacement: path.resolve(import.meta.dirname, 'packages/web/tool-web/src') },
      { find: '@flowforge/workflow/src', replacement: path.resolve(import.meta.dirname, 'packages/workflow/workflow/src') },
      { find: '@flowforge/workflow', replacement: path.resolve(import.meta.dirname, 'packages/workflow/workflow/src') },
      { find: '@flowforge/persona/src', replacement: path.resolve(import.meta.dirname, 'packages/preset/persona/src') },
      { find: '@flowforge/persona', replacement: path.resolve(import.meta.dirname, 'packages/preset/persona/src') },
      { find: '@flowforge/sandbox/src', replacement: path.resolve(import.meta.dirname, 'packages/sandbox/sandbox/src') },
      { find: '@flowforge/sandbox', replacement: path.resolve(import.meta.dirname, 'packages/sandbox/sandbox/src') },
      { find: '@flowforge/session/src', replacement: path.resolve(import.meta.dirname, 'packages/core/session/src') },
      { find: '@flowforge/session', replacement: path.resolve(import.meta.dirname, 'packages/core/session/src') },
      { find: '@flowforge/storage/src', replacement: path.resolve(import.meta.dirname, 'packages/storage/storage/src') },
      { find: '@flowforge/storage', replacement: path.resolve(import.meta.dirname, 'packages/storage/storage/src') },
      { find: '@flowforge/timeout/src', replacement: path.resolve(import.meta.dirname, 'packages/util/timeout/src') },
      { find: '@flowforge/timeout', replacement: path.resolve(import.meta.dirname, 'packages/util/timeout/src') },
      { find: '@flowforge/tool-fs/src', replacement: path.resolve(import.meta.dirname, 'packages/fs/tool-fs/src') },
      { find: '@flowforge/tool-fs', replacement: path.resolve(import.meta.dirname, 'packages/fs/tool-fs/src') },
      { find: '@flowforge/canary/src', replacement: path.resolve(import.meta.dirname, 'packages/plugins/canary/src') },
      { find: '@flowforge/canary', replacement: path.resolve(import.meta.dirname, 'packages/plugins/canary/src') },
      // Explicit index.ts: a bare directory falls through to the package.json
      // `main` (lib/index.js bundle), whose tsc build inlines away the
      // `FiberState` const enum and breaks runtime imports of it.
      { find: '@flowforge/cordis', replacement: path.resolve(import.meta.dirname, 'vendor/cordis/src/index.ts') },
      { find: '@flowforge/fs-e2b/src', replacement: path.resolve(import.meta.dirname, 'packages/e2b/fs-e2b/src') },
      { find: '@flowforge/fs-e2b', replacement: path.resolve(import.meta.dirname, 'packages/e2b/fs-e2b/src') },
      { find: '@flowforge/agent/src', replacement: path.resolve(import.meta.dirname, 'packages/core/agent/src') },
      { find: '@flowforge/agent', replacement: path.resolve(import.meta.dirname, 'packages/core/agent/src') },
      { find: '@flowforge/brand/src', replacement: path.resolve(import.meta.dirname, 'packages/util/brand/src') },
      { find: '@flowforge/brand', replacement: path.resolve(import.meta.dirname, 'packages/util/brand/src') },
      { find: '@flowforge/guard/src', replacement: path.resolve(import.meta.dirname, 'packages/plugins/guard/src') },
      { find: '@flowforge/guard', replacement: path.resolve(import.meta.dirname, 'packages/plugins/guard/src') },
      { find: '@flowforge/modes/src', replacement: path.resolve(import.meta.dirname, 'packages/plugins/modes/src') },
      { find: '@flowforge/modes', replacement: path.resolve(import.meta.dirname, 'packages/plugins/modes/src') },
      { find: '@flowforge/scope/src', replacement: path.resolve(import.meta.dirname, 'packages/core/scope/src') },
      { find: '@flowforge/scope', replacement: path.resolve(import.meta.dirname, 'packages/core/scope/src') },
      { find: '@flowforge/shell/src', replacement: path.resolve(import.meta.dirname, 'packages/shell/shell/src') },
      { find: '@flowforge/shell', replacement: path.resolve(import.meta.dirname, 'packages/shell/shell/src') },
      { find: '@flowforge/skill/src', replacement: path.resolve(import.meta.dirname, 'packages/skill/skill/src') },
      { find: '@flowforge/skill', replacement: path.resolve(import.meta.dirname, 'packages/skill/skill/src') },
      { find: '@flowforge/spill/src', replacement: path.resolve(import.meta.dirname, 'packages/spill/spill/src') },
      { find: '@flowforge/spill', replacement: path.resolve(import.meta.dirname, 'packages/spill/spill/src') },
      { find: '@flowforge/tools/src', replacement: path.resolve(import.meta.dirname, 'packages/core/tools/src') },
      { find: '@flowforge/tools', replacement: path.resolve(import.meta.dirname, 'packages/core/tools/src') },
      { find: '@flowforge/goal/src', replacement: path.resolve(import.meta.dirname, 'packages/goal/goal/src') },
      { find: '@flowforge/goal', replacement: path.resolve(import.meta.dirname, 'packages/goal/goal/src') },
      { find: '@flowforge/jobs/src', replacement: path.resolve(import.meta.dirname, 'packages/jobs/jobs/src') },
      { find: '@flowforge/jobs', replacement: path.resolve(import.meta.dirname, 'packages/jobs/jobs/src') },
      { find: '@flowforge/acp/src', replacement: path.resolve(import.meta.dirname, 'packages/acp/acp/src') },
      { find: '@flowforge/acp', replacement: path.resolve(import.meta.dirname, 'packages/acp/acp/src') },
      { find: '@flowforge/e2b/src', replacement: path.resolve(import.meta.dirname, 'packages/e2b/e2b/src') },
      { find: '@flowforge/e2b', replacement: path.resolve(import.meta.dirname, 'packages/e2b/e2b/src') },
      { find: '@flowforge/llm/src', replacement: path.resolve(import.meta.dirname, 'packages/llm/llm/src') },
      { find: '@flowforge/llm', replacement: path.resolve(import.meta.dirname, 'packages/llm/llm/src') },
      { find: '@flowforge/lsp/src', replacement: path.resolve(import.meta.dirname, 'packages/lsp/lsp/src') },
      { find: '@flowforge/lsp', replacement: path.resolve(import.meta.dirname, 'packages/lsp/lsp/src') },
      { find: '@flowforge/web/src', replacement: path.resolve(import.meta.dirname, 'packages/web/web/src') },
      { find: '@flowforge/web', replacement: path.resolve(import.meta.dirname, 'packages/web/web/src') },
      { find: '@flowforge/fs/src', replacement: path.resolve(import.meta.dirname, 'packages/fs/fs/src') },
      { find: '@flowforge/fs', replacement: path.resolve(import.meta.dirname, 'packages/fs/fs/src') },
      { find: '@flowforge/client-connection/src', replacement: path.resolve(import.meta.dirname, 'packages/client/connection/src') },
      { find: '@flowforge/client-connection', replacement: path.resolve(import.meta.dirname, 'packages/client/connection/src') },
      { find: '@flowforge/api-gateway/src', replacement: path.resolve(import.meta.dirname, 'packages/api/gateway/src') },
      { find: '@flowforge/api-gateway', replacement: path.resolve(import.meta.dirname, 'packages/api/gateway/src') },
      { find: '@flowforge/api-remotes/src', replacement: path.resolve(import.meta.dirname, 'packages/api/remotes/src') },
      { find: '@flowforge/api-remotes', replacement: path.resolve(import.meta.dirname, 'packages/api/remotes/src') },
      { find: '@flowforge/host-webserver/src', replacement: path.resolve(import.meta.dirname, 'packages/host/webserver/src') },
      { find: '@flowforge/host-webserver', replacement: path.resolve(import.meta.dirname, 'packages/host/webserver/src') },
      { find: '@flowforge/host-apiproxy/client', replacement: path.resolve(import.meta.dirname, 'packages/host/apiproxy/src/fetch/client.ts') },
      { find: '@flowforge/host-apiproxy/src', replacement: path.resolve(import.meta.dirname, 'packages/host/apiproxy/src') },
      { find: '@flowforge/host-apiproxy', replacement: path.resolve(import.meta.dirname, 'packages/host/apiproxy/src') },
      { find: '@flowforge/host-directory-picker-browse/src', replacement: path.resolve(import.meta.dirname, 'packages/host/directory-picker-browse/src') },
      { find: '@flowforge/host-directory-picker-browse', replacement: path.resolve(import.meta.dirname, 'packages/host/directory-picker-browse/src') },
      { find: '@flowforge/host-directory-picker-native/src', replacement: path.resolve(import.meta.dirname, 'packages/host/directory-picker-native/src') },
      { find: '@flowforge/host-directory-picker-native', replacement: path.resolve(import.meta.dirname, 'packages/host/directory-picker-native/src') },
      { find: '@flowforge/host-directory-picker/src', replacement: path.resolve(import.meta.dirname, 'packages/host/directory-picker/src') },
      { find: '@flowforge/host-directory-picker', replacement: path.resolve(import.meta.dirname, 'packages/host/directory-picker/src') },
      { find: '@flowforge/host-frontend-static/src', replacement: path.resolve(import.meta.dirname, 'packages/host/frontend-static/src') },
      { find: '@flowforge/host-frontend-static', replacement: path.resolve(import.meta.dirname, 'packages/host/frontend-static/src') },
      { find: '@flowforge/host-plugin-inventory/src', replacement: path.resolve(import.meta.dirname, 'packages/host/plugin-inventory/src') },
      { find: '@flowforge/host-plugin-inventory', replacement: path.resolve(import.meta.dirname, 'packages/host/plugin-inventory/src') },
      { find: '@flowforge/cmdline/src', replacement: path.resolve(import.meta.dirname, 'packages/boot/cmdline/src') },
      { find: '@flowforge/cmdline', replacement: path.resolve(import.meta.dirname, 'packages/boot/cmdline/src') },
      { find: '@flowforge/base/src', replacement: path.resolve(import.meta.dirname, 'packages/bundle/base/src') },
      { find: '@flowforge/base', replacement: path.resolve(import.meta.dirname, 'packages/bundle/base/src') },
      { find: '@flowforge/headless/src', replacement: path.resolve(import.meta.dirname, 'packages/bundle/headless/src') },
      { find: '@flowforge/headless', replacement: path.resolve(import.meta.dirname, 'packages/bundle/headless/src') },
      { find: '@flowforge/plugins-video-protocol/src', replacement: path.resolve(import.meta.dirname, 'packages/plugins/video-protocol/src') },
      { find: '@flowforge/plugins-video-protocol', replacement: path.resolve(import.meta.dirname, 'packages/plugins/video-protocol/src') },
      { find: '@flowforge/plugins-video-analysis/src', replacement: path.resolve(import.meta.dirname, 'packages/plugins/video-analysis/src') },
      { find: '@flowforge/plugins-video-analysis', replacement: path.resolve(import.meta.dirname, 'packages/plugins/video-analysis/src') },
      { find: '@flowforge/plugins-video-gen/src', replacement: path.resolve(import.meta.dirname, 'packages/plugins/video-gen/src') },
      { find: '@flowforge/plugins-video-gen', replacement: path.resolve(import.meta.dirname, 'packages/plugins/video-gen/src') },
      { find: '@flowforge/harness-env-registry/src', replacement: path.resolve(import.meta.dirname, 'packages/harness/env-registry/src') },
      { find: '@flowforge/harness-env-registry', replacement: path.resolve(import.meta.dirname, 'packages/harness/env-registry/src') },
      // <generated-alias:end>
]

// Workspace projects inherit NEITHER the root resolve.alias NOR the root test
// config; timeouts and inline-deps must be repeated on every project, or the
// 5s vitest defaults silently apply inside the fork pools.
const projectTestBase = {
  testTimeout: 30_000,
  hookTimeout: 30_000,
  server: {
    deps: {
      inline: [/@flowforge\/.*/],
    },
  },
}

export default defineConfig({
  plugins: [standardDecoratorPlugin()],
  resolve: {
    alias: aliasEntries,
  },
  test: {
    environment: 'node',
    // process-bound suites (session-persistence-jsonl) and torn-frame
    // decoding are timing-sensitive under full-suite parallelism on Windows;
    // the flowforge upstream runs them in a dedicated fork project.
    testTimeout: 30_000,
    hookTimeout: 30_000,
    // pnpm declares the workspace in pnpm-workspace.yaml, which vitest does not
    // auto-discover; inline @flowforge/* so every package import goes through
    // the Vite transform pipeline (alias + package-exports self-resolution)
    // instead of Node's bare-module lookup.
    server: {
      deps: {
        inline: [/@flowforge\/.*/],
      },
    },
    projects: [
      {
        plugins: [standardDecoratorPlugin()],
        resolve: { alias: aliasEntries },
        test: {
          name: 'thread-safe',
          pool: 'forks',
          ...projectTestBase,
          include: testInclude,
          exclude: [...testExclude, ...processBoundTests],
        },
      },
      {
        plugins: [standardDecoratorPlugin()],
        resolve: { alias: aliasEntries },
        test: {
          name: 'process-bound',
          pool: 'forks',
          ...projectTestBase,
          include: processBoundTests,
          exclude: testExclude,
        },
      },
    ],
    coverage: {
      provider: 'v8',
      include: ['packages/**/src/**'],
    },
  },
})
