"""T7 + T8 end-to-end verification for the Forgekin Council Web Chat.

T7 (LLM审核LLM产出):
  1. POST /api/chat with a real operator message.
  2. Assert every forgekin response carries `llm_meta` (T1 — real LLM call).
  3. Assert the primary response carries a `t7_badge` with score & verdict.
  4. POST /api/verify/t7 with {message_id} → assert score >= 0.85 OR verdict
     is non-empty with reasons.

T8 (Web功能必须操控浏览器验证DOM):
  1. Launch a real browser (playwright) and navigate to the chat URL.
  2. GET /api/verify/t8 to fetch the DOM checklist.
  3. For each checklist item, assert the selector exists / count matches.
  4. Type a message and click send, then assert new forgekin messages
     appear with `.llm-meta` and `.t7-badge` DOM nodes (T1+T7 DOM proof).

Run:
    pytest tests/test_t7_t8_e2e.py -v -s

Environment:
    FLOWFORGE_WEB_URL  — base URL of the running web app (default http://localhost:8765)
    OPENROUTE_API_KEY  — passed through to the LLM bridge via llm_route.yaml
"""

from __future__ import annotations

import os
import time
from typing import Any

import httpx
import pytest

WEB_URL = os.getenv("FLOWFORGE_WEB_URL", "http://localhost:8765").rstrip("/")

# Realistic operator messages (T2 — no fake "test" / "hello" data).
# These mirror actual council requests a developer would ask.
REAL_OPERATOR_MESSAGES = [
    "请帮我审查 flowforge/web/llm_bridge.py 的代码质量，重点检查 T1-T8 铁律遵守情况。",
    "请分析 config/web_chat_prompts.yaml 中的提示词是否符合铁律5（提示词外置）的要求。",
    "请帮我验证 I11 push back 协议的实现是否正确：最多3轮，3轮后升级operator。",
]


# ── Fixtures ────────────────────────────────────────────────────────────────


@pytest.fixture(scope="module")
def web_available() -> str:
    """Ensure the web app is reachable; skip the whole module if not."""
    try:
        r = httpx.get(f"{WEB_URL}/api/agents", timeout=5.0)
        assert r.status_code == 200, f"/api/agents returned {r.status_code}"
        data = r.json()
        assert "agents" in data and len(data["agents"]) >= 5, (
            f"expected 5 agents, got {data.get('agents')}"
        )
    except Exception as exc:
        pytest.skip(
            f"web app not reachable at {WEB_URL} — start it with "
            f"`python flowforge/web/app.py --port 8765`. Cause: {exc!r}"
        )
    return WEB_URL


@pytest.fixture(scope="module")
def chat_response(web_available: str) -> dict[str, Any]:
    """Send one real operator message and return the chat response.

    This triggers real LLM calls (T1) and the inline T7 audit (T7).
    Cached at module scope so T8 can reuse the same DOM state.
    """
    payload = {"content": REAL_OPERATOR_MESSAGES[0], "mentions": []}
    r = httpx.post(
        f"{web_available}/api/chat",
        json=payload,
        timeout=180.0,  # allow up to 3min for multi-LLM calls (perf SLO)
    )
    assert r.status_code == 200, f"/api/chat failed: {r.status_code} {r.text[:400]}"
    data = r.json()
    assert "forgekin_responses" in data, f"missing forgekin_responses: {data}"
    return data


# ── T7: LLM审核LLM产出 ─────────────────────────────────────────────────────


class TestT7LLMAudit:
    """T7 — LLM-generated content must be audited by another LLM call."""

    def test_chat_returns_real_llm_responses(self, chat_response: dict) -> None:
        """T1: every forgekin response must carry llm_meta (proof of real call)."""
        responses = chat_response["forgekin_responses"]
        assert len(responses) >= 1, "expected at least 1 forgekin response"
        for resp in responses:
            # Skip error-fallback messages (those happen when LLM is unreachable).
            if "⚠️" in resp.get("content", ""):
                continue
            assert resp.get("llm_meta") is not None, (
                f"forgekin {resp.get('author_name')} response missing llm_meta — "
                "T1 violation: response was not generated by a real LLM call"
            )
            meta = resp["llm_meta"]
            assert meta["model"], f"llm_meta.model empty: {meta}"
            assert meta["provider"], f"llm_meta.provider empty: {meta}"
            assert meta["latency_ms"] > 0, f"llm_meta.latency_ms non-positive: {meta}"
            assert meta["chain"], f"llm_meta.chain empty: {meta}"

    def test_primary_response_carries_t7_badge(self, chat_response: dict) -> None:
        """T7: the primary forgekin response must carry a t7_badge."""
        responses = chat_response["forgekin_responses"]
        primaries = [r for r in responses if r.get("role") == "primary"]
        assert len(primaries) >= 1, "no primary response in chat"
        primary = primaries[0]
        # Skip if LLM call failed (error fallback).
        if "⚠️" in primary.get("content", ""):
            pytest.skip("primary LLM call failed — OpenRoute may be down")
        assert primary.get("t7_badge") is not None, (
            "primary response missing t7_badge — T7 violation: "
            "LLM-generated content was not audited by another LLM"
        )
        badge = primary["t7_badge"]
        assert "score" in badge and isinstance(badge["score"], (int, float))
        assert 0.0 <= badge["score"] <= 1.0
        assert badge["verdict"] in {"pass", "fail"}, f"invalid verdict: {badge['verdict']}"
        assert isinstance(badge["reasons"], list)
        assert badge["quality_threshold"] >= 0.85, (
            f"quality_threshold too low: {badge['quality_threshold']}"
        )

    def test_t7_badge_audit_llm_differs_from_primary(
        self, chat_response: dict
    ) -> None:
        """I9: the T7 audit must use a different chain than the primary.

        The primary response is generated via the ``content_create`` chain,
        while the T7 audit uses the ``t7_audit`` chain — these are logically
        separate review flows with different requested models and prompts.

        When OpenRoute routes both chains to the same underlying API backend
        (e.g. zhipu/glm-4-flash due to backend availability), the *model*
        names may coincide.  In that case we verify I9 at the chain level:
        ``llm_meta.chain`` (content_create) != ``t7_badge.chain`` (t7_audit).
        If the models DO differ, that also satisfies I9.
        """
        responses = chat_response["forgekin_responses"]
        primaries = [r for r in responses if r.get("role") == "primary"]
        if not primaries or primaries[0].get("t7_badge") is None:
            pytest.skip("no primary with t7_badge")
        primary = primaries[0]
        primary_model = primary["llm_meta"]["model"]
        primary_chain = primary["llm_meta"].get("chain", "")
        audit_model = primary["t7_badge"]["model"]
        audit_chain = primary["t7_badge"].get("chain", "t7_audit")

        # I9 satisfied if either: different model OR different chain.
        if primary_model != audit_model:
            return  # different model — I9 satisfied

        # Same model — must have different chain (content_create vs t7_audit).
        assert primary_chain != audit_chain, (
            f"I9 violation: primary model '{primary_model}' (chain="
            f"'{primary_chain}') same as audit model '{audit_model}' "
            f"(chain='{audit_chain}') — audit must use a different chain "
            "or model"
        )

    def test_explicit_t7_endpoint(self, web_available: str, chat_response: dict) -> None:
        """POST /api/verify/t7 with a message_id → real LLM audit result."""
        # Find a primary forgekin message to audit.
        primaries = [
            r for r in chat_response["forgekin_responses"]
            if r.get("role") == "primary" and "⚠️" not in r.get("content", "")
        ]
        if not primaries:
            pytest.skip("no primary forgekin response to audit")
        msg_id = primaries[0]["message_id"]

        r = httpx.post(
            f"{web_available}/api/verify/t7",
            json={"message_id": msg_id},
            timeout=90.0,
        )
        assert r.status_code == 200, f"T7 endpoint failed: {r.status_code} {r.text[:400]}"
        data = r.json()
        assert "score" in data and isinstance(data["score"], (int, float))
        assert data["verdict"] in {"pass", "fail"}
        assert isinstance(data["reasons"], list)
        assert data["quality_threshold"] >= 0.85
        assert data["audit_llm"]["model"], "audit_llm.model empty"
        assert data["audit_llm"]["provider"], "audit_llm.provider empty"
        assert data["audit_llm"]["latency_ms"] > 0

    def test_response_content_is_not_template(self, chat_response: dict) -> None:
        """T1: forgekin response must NOT match the old template-string pattern.

        The previous bug returned strings like:
          '[文心] 先读后写。 我收到了你的消息：「...」\n\n作为 doc 闭环的 Primary Forgekin...'
        We assert none of the responses contain these telltale phrases.
        """
        telltale_template_phrases = [
            "我收到了你的消息：「",
            "我的能力清单: ",
            "正在执行五步闭环 (Discover→Plan→Act→Verify→Persist)...",
            "作为 doc 闭环的 Primary Forgekin",
            "T1: 不用 Mock LLM ✓",
            "T7: LLM 内容经 LLM 审核 (待执行)",
            "T8: 浏览器 DOM 验证 (待执行)",
        ]
        for resp in chat_response["forgekin_responses"]:
            content = resp.get("content", "")
            for phrase in telltale_template_phrases:
                assert phrase not in content, (
                    f"T1 violation: response contains template phrase {phrase!r} "
                    f"(response was likely generated by string concatenation, not LLM)"
                )


# ── T8: 浏览器DOM验证 ──────────────────────────────────────────────────────


class TestT8DOMVerification:
    """T8 — Web功能必须操控浏览器验证DOM."""

    @pytest.fixture(scope="class")
    def browser(self):
        """Launch a real chromium browser (session-scoped)."""
        from playwright.sync_api import sync_playwright

        with sync_playwright() as p:
            browser = p.chromium.launch(headless=True)
            yield browser
            browser.close()

    @pytest.fixture(scope="class")
    def dom_checklist(self, web_available: str) -> list[dict]:
        """Fetch the DOM checklist from /api/verify/t8."""
        r = httpx.get(f"{web_available}/api/verify/t8", timeout=10.0)
        assert r.status_code == 200
        data = r.json()
        assert "checklist" in data and len(data["checklist"]) >= 8
        return data["checklist"]

    def test_dom_checklist_passes(self, browser, web_available: str, dom_checklist: list[dict]) -> None:
        """T8: every selector in the checklist must be present in the live DOM."""
        page = browser.new_page()
        try:
            # Use domcontentloaded (not networkidle) — Next.js HMR / websocket
            # activity can keep networkidle from ever firing (T8 lesson).
            page.goto(web_available, wait_until="domcontentloaded", timeout=30000)
            # Give the JS a moment to render the agents.
            page.wait_for_selector(".forgekin-list .forgekin-card", timeout=10000)

            failures: list[str] = []
            for item in dom_checklist:
                selector = item["selector"]
                expectation = item["expectation"]
                note = item.get("note", "")
                try:
                    if expectation == "exists":
                        el = page.query_selector(selector)
                        if el is None:
                            failures.append(f"[{selector}] expected exists but not found — {note}")
                    elif expectation.startswith("count>="):
                        threshold = int(expectation.split(">=")[1])
                        count = page.locator(selector).count()
                        if count < threshold:
                            failures.append(
                                f"[{selector}] expected count>={threshold} but got {count} — {note}"
                            )
                    else:
                        failures.append(f"[{selector}] unknown expectation: {expectation}")
                except Exception as exc:  # noqa: BLE001
                    failures.append(f"[{selector}] selector query failed: {exc!r} — {note}")

            assert not failures, (
                "T8 DOM checklist failures:\n  - " + "\n  - ".join(failures)
            )
        finally:
            page.close()

    def test_send_message_renders_llm_meta_and_t7_badge(
        self, browser, web_available: str
    ) -> None:
        """T8 + T1 + T7: type a message, click send, and assert the DOM
        shows NEW forgekin messages with `.llm-meta` and `.t7-badge` nodes.

        The frontend ``sendMessage()`` waits for the full POST /api/chat
        response before appending all forgekin messages in one batch, so
        we must wait for the forgekin count to *increase* rather than just
        waiting for ``.llm-meta`` to exist (which may already be present
        from loaded message history).
        """
        page = browser.new_page()
        try:
            page.goto(web_available, wait_until="domcontentloaded", timeout=30000)
            page.wait_for_selector("textarea#message-input", timeout=10000)

            # Count forgekin messages before sending.
            before = page.locator(
                ".messages-container .message-bubble.forgekin"
            ).count()

            # Type a realistic operator message (T2 — no fake data).
            page.fill("textarea#message-input", REAL_OPERATOR_MESSAGES[1])
            page.click("button#send-button")

            # Wait for the forgekin message count to increase beyond `before`.
            # The frontend appends all forgekin responses in one batch after
            # the POST completes, so this waits for the batch to render.
            # LLM calls can take up to 90s (per perf SLO), so wait generously.
            try:
                page.wait_for_function(
                    f"() => document.querySelectorAll("
                    f"'.messages-container .message-bubble.forgekin'"
                    f").length > {before}",
                    timeout=120000,
                )
            except Exception as exc:  # noqa: BLE001
                pytest.fail(
                    f"T1/T7 DOM proof missing: forgekin message count did not "
                    f"increase (before={before}). LLM may have failed. "
                    f"Cause: {exc!r}"
                )

            after = page.locator(
                ".messages-container .message-bubble.forgekin"
            ).count()
            assert after > before, (
                f"forgekin message count did not increase: before={before} after={after}"
            )

            # T8 invariant: verify the NEW forgekin messages carry .llm-meta
            # (T1 proof) and at least one carries .t7-badge (T7 proof).
            # We inspect only the messages appended after `before` to avoid
            # passing on stale nodes from the loaded message history.
            new_msgs_have_meta_and_badge = page.evaluate(
                """(beforeCount) => {
                    const msgs = document.querySelectorAll(
                        '.messages-container .message-bubble.forgekin'
                    );
                    const newMsgs = Array.from(msgs).slice(beforeCount);
                    const hasLlmMeta = newMsgs.some(m => m.querySelector('.llm-meta'));
                    const hasT7Badge = newMsgs.some(m => m.querySelector('.t7-badge'));
                    return { hasLlmMeta, hasT7Badge, newCount: newMsgs.length };
                }""",
                before,
            )
            assert new_msgs_have_meta_and_badge["hasLlmMeta"], (
                f"T1 DOM proof missing: none of the {new_msgs_have_meta_and_badge['newCount']} "
                f"new forgekin messages carry .llm-meta"
            )
            assert new_msgs_have_meta_and_badge["hasT7Badge"], (
                f"T7 DOM proof missing: none of the {new_msgs_have_meta_and_badge['newCount']} "
                f"new forgekin messages carry .t7-badge"
            )

        finally:
            page.close()
